name: Publish to Nuget

on:
  release:
    types: [published]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build -c Release --no-restore 
    - name: Test
      run: dotnet test -c Release --no-build --verbosity normal
    - name: Pack
      run: dotnet pack -c Release --no-build
    - name: Publish
      run: dotnet nuget push src/NCalcAsync/bin/Release/NCalcAsync.*nupkg -k "${{ secrets.NUGET_API_TOKEN }}" -s https://api.nuget.org/v3/index.json
